/*
 * TIMER0_config.h
 *
 *  Created on: Nov 3, 2018
 *      Author: Mostafa
 */

#ifndef MCAL_TIMER0_TIMER0_CONFIG_H_
#define MCAL_TIMER0_TIMER0_CONFIG_H_

/*
 * choose between
 * TIMER0_MODE_CTC_MSK
 * TIMER0_MODE_NORMAL_MSK
 * TIMER0_MODE_FAST_PWM_MSK
 * TIMER0_MODE_PHASE_CORRECT
 * */
#define TIMER0_MODE_SELECTOR_MSK		TIMER0_MODE_CTC_MSK

/*
 * if you choose PWM PWM mode
 * choose between
 * TIMER0_FAST_PWM_START_HIGH_MSK
 * TIMER0_FAST_PWM_START_LOW_MSK
 * */
#define TIMER0_FAST_PWM_START_EDGE_MSK		TIMER0_FAST_PWM_START_HIGH_MSK

/*
 * choose between
 * TIMER0_PRESCALER_1
 * TIMER0_PRESCALER_8
 * TIMER0_PRESCALER_64
 * TIMER0_PRESCALER_256
 * TIMER0_PRESCALER_1024
 * */
#define TIMER0_PRESCALER_SELECTOR_MSK	TIMER0_PRESCALER_64

#define TIMER0_DESIRED_STEPS			125

#endif /* MCAL_TIMER0_TIMER0_CONFIG_H_ */
